name: music_app
description: Music Player App
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  provider: ^6.1.1
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1
  http: ^1.1.0

flutter:
  uses-material-design: true
